export enum ErrorKeys {
  SHOPPING_LIST_NOT_FOUND = 'SHOPPING_LIST_NOT_FOUND',
  SHOPPING_LIST_ITEM_NOT_FOUND = 'SHOPPING_LIST_ITEM_NOT_FOUND',
  SHOPPING_LIST_CREATION_FAILED = 'SHOPPING_LIST_CREATION_FAILED',
  SHOPPING_LIST_UPDATE_FAILED = 'SHOPPING_LIST_UPDATE_FAILED',
  SHOPPING_LIST_ITEM_CREATION_FAILED = 'SHOPPING_LIST_ITEM_CREATION_FAILED',
  SHOPPING_LIST_ITEM_UPDATE_FAILED = 'SHOPPING_LIST_ITEM_UPDATE_FAILED',
  USER_NOT_OWNER = 'USER_NOT_OWNER',
}
