const mexicanPantry = {
  aromatics: ['White Onion', 'Red Onion', 'Scallion', 'Garlic'],
  cookingFats: ['Butter', 'Olive Oil', 'Vegetable Oil', 'Lard'],
  cookingAcids: [
    'Lime Juice',
    'Orange Juice',
    'Lime',
    'Tomatillo',
    'White Vinegar',
    'Apple Cider Vinegar',
    'Sugarcane Vinegar',
  ],
  garnishingAcids: [
    'Queso Oaxaca',
    'Queso Fresco',
    'Cotija Cheese',
    'Panela Cheese',
    'Pickled Jalapeño',
  ],
  floursAndMeals: ['Masa Harina'],
  wholeGrains: ['Long Grain White Rice'],
  breads: ['Flour Tortilla', 'Corn Tortilla'],
  noodles: ['Vermicelli', 'Angel Hair Pasta'],
  starchyVeg: ['Jicama', 'Hominy', 'Corn', 'Russet Potato'],
  nutsAndSeeds: ['Pumpkin Seeds', 'Sesame Seeds', 'Pecan', 'Walnut', 'Peanut'],
  redOrangeVeg: ['Canned Tomato'],
  pulses: [
    'Canned Pinto Beans',
    'Canned Black Beans',
    'Dried Peruano Beans',
    'Dried Pinto Beans',
    'Dried Black Beans',
    'Refried Pinto Beans',
  ],
  otherVeg: [
    'Avocado',
    'Poblano Pepper',
    'Serrano Pepper',
    'Jalapeño Pepper',
    'Habanero Pepper',
    'Guajillo Chile',
    'Ancho Chile',
    'Chipotle Chile',
    'Chile de Árbol',
    'Nopal',
  ],
  sweeteners: [
    'Piloncillo',
    'Mexican Chocolate',
    'Vanilla Extract',
    'Vanilla Bean',
  ],
  herbs: [
    'Cilantro',
    'Mint',
    'Mexican Oregano',
    'Thyme',
    'Bay Leaf',
    'Epazote',
    'Dried Hibiscus Flower',
  ],
  spices: [
    'Cayenne Powder',
    'Garlic Powder',
    'Onion Powder',
    'Whole Allspice',
    'Ground Allspice',
    'Ground Cumin',
    'Cumin Seed',
    'Ground Coriander',
    'Chili Powder',
    'Whole Clove',
    'Cinnamon Stick',
    'Ground Cinnamon',
  ],
  saucesAndstockBases: [
    'Chicken Bouillion Powder',
    'Chipotles In Adobo Sauce',
    'Achiote Paste',
  ],
  fruits: ['Tamarind'],
  meats: ['Chorizo'],
  miscellaneous: ['Corn Husk'],
}
