export enum ErrorKeys {
  BRAND_NOT_FOUND = 'BRAND_NOT_FOUND',
  BRAND_NAME_DUPLICATE = 'BRAND_NAME_DUPLICATE',
  INVALID_BRAND_DATA = 'INVALID_BRAND_DATA',
  FAILURE_TO_CREATE_BRAND = 'FAILURE_TO_CREATE_BRAND',
}
